[features]
seeds = false
[programs.localnet]
tansu_nft = "3nLgLxquBkVFH3AKKraAa95LG2UAv6c5dpTXAB5yvuHU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/shintaro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
